version: "3.9"
name: databackend

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: databackend
      POSTGRES_USER: databackend
      POSTGRES_PASSWORD: databackend
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U databackend']
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  analytics:
    image: postgres:latest
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U analytics']
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - analytics-db:/var/lib/postgresql/data
    ports:
      - "5435:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
       - ./pgadmin/postgreslocal-servers-config.json:/pgadmin4/servers.json
    ports:
      - "5050:80"

volumes:
  db:
  pgadmin:
  analytics-db: